# Generated by Django 5.1.6 on 2025-02-20 20:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_car_model_alter_aftosalon_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car_model',
            options={'ordering': ['created_ed'], 'verbose_name': 'Car_model', 'verbose_name_plural': 'Car_models'},
        ),
        migrations.AddField(
            model_name='car',
            name='created_ed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Aftosalon',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
